apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/scheme":"https","prometheus.io/scrape":"true","service.alpha.openshift.io/serving-cert-secret-name":"webconsole-serving-cert"},"labels":{"app":"openshift-web-console"},"name":"webconsole","namespace":"openshift-web-console"},"spec":{"ports":[{"name":"https","port":443,"targetPort":8443}],"selector":{"webconsole":"true"}}}
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
    service.alpha.openshift.io/serving-cert-secret-name: webconsole-serving-cert
    service.alpha.openshift.io/serving-cert-signed-by: openshift-service-serving-signer@1591884868
  creationTimestamp: 2020-06-11T14:21:53Z
  labels:
    app: openshift-web-console
  name: webconsole
  namespace: openshift-web-console
  resourceVersion: "2436"
  selfLink: /api/v1/namespaces/openshift-web-console/services/webconsole
  uid: e5d0fd42-abee-11ea-86f8-0800273f7cc9
spec:
  clusterIP: 172.30.142.50
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    webconsole: "true"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
