apiVersion: v1
data:
  webconsole-config.yaml: |
    apiVersion: webconsole.config.openshift.io/v1
    clusterInfo:
      adminConsolePublicURL: https://console.app.192.168.0.102.nip.io/
      consolePublicURL: https://master.192.168.0.101.nip.io:8443/console/
      loggingPublicURL: ''
      logoutPublicURL: ''
      masterPublicURL: https://master.192.168.0.101.nip.io:8443
      metricsPublicURL: ''
    extensions:
      properties: {}
      scriptURLs: []
      stylesheetURLs: []
    features:
      clusterResourceOverridesEnabled: false
      inactivityTimeoutMinutes: 0
    kind: WebConsoleConfiguration
    servingInfo:
      bindAddress: 0.0.0.0:8443
      bindNetwork: tcp4
      certFile: /var/serving-cert/tls.crt
      clientCA: ''
      keyFile: /var/serving-cert/tls.key
      maxRequestsInFlight: 0
      namedCertificates: null
      requestTimeoutSeconds: 0
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"webconsole-config.yaml":"apiVersion: webconsole.config.openshift.io/v1\nclusterInfo:\n  adminConsolePublicURL: https://console.app.192.168.0.102.nip.io/\n  consolePublicURL: https://master.192.168.0.101.nip.io:8443/console/\n  loggingPublicURL: ''\n  logoutPublicURL: ''\n  masterPublicURL: https://master.192.168.0.101.nip.io:8443\n  metricsPublicURL: ''\nextensions:\n  properties: {}\n  scriptURLs: []\n  stylesheetURLs: []\nfeatures:\n  clusterResourceOverridesEnabled: false\n  inactivityTimeoutMinutes: 0\nkind: WebConsoleConfiguration\nservingInfo:\n  bindAddress: 0.0.0.0:8443\n  bindNetwork: tcp4\n  certFile: /var/serving-cert/tls.crt\n  clientCA: ''\n  keyFile: /var/serving-cert/tls.key\n  maxRequestsInFlight: 0\n  namedCertificates: null\n  requestTimeoutSeconds: 0\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"openshift-web-console"},"name":"webconsole-config","namespace":"openshift-web-console"}}
  creationTimestamp: 2020-06-11T14:21:53Z
  labels:
    app: openshift-web-console
  name: webconsole-config
  namespace: openshift-web-console
  resourceVersion: "2415"
  selfLink: /api/v1/namespaces/openshift-web-console/configmaps/webconsole-config
  uid: e5c849e0-abee-11ea-86f8-0800273f7cc9
